on:
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: action/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Compile code
        run: javac src/main/java/com/sheridan/App.java

      - name: Run code
        run: java -cp src/main/java com.sheridan.App
